import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
//Components
import { Hero } from '../components/Hero'
import { Catalog } from '../components/Catalog'
import { Gallery } from '../components/Gallery'

const galleryFetched = [
  {
    title:"Ropa urbana en medellín",
    src: "https://www.greazy.shop/8842c4f85d8a5fd312aa.jpg",
    featured: true
  },
  {
    title:"Ropa urbana en medellín",
    src: "https://www.greazy.shop/95266502196f581360b0.jpg",
    featured: false
  },
  {
    title:"Ropa urbana en medellín",
    src: "https://www.greazy.shop/8842c4f85d8a5fd312aa.jpg",
    featured: false
  },
  {
    title:"Ropa urbana en medellín",
    src: "https://www.greazy.shop/80bfd0d67142df909c87.jpg",
    featured: false
  }
]
export default function Home() {
  const [galleryPhotos, setGalleryPhotos] = useState(null)
  const [featuredPhoto, setFeaturedPhoto] = useState(null)
  useEffect(() => {
    setTimeout(()=>{
      setGalleryPhotos(galleryFetched);
      setFeaturedPhoto(galleryFetched.filter(photo => photo.featured)[0])
    }, 1000)
  
  }, [])
  
  return (
    <div>
      <Head>
        <title>Greazy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />        
      </Head>
      <header className="header">
        <div className="header__logo">
          <Image src="/assets/logo.png" alt="me" layout={'fill'} objectFit={'contain'} />
        </div>
      </header>
      <Hero/>

      <Catalog/>
      <section className="about__greazy">
        {
          featuredPhoto ?
            <div className="about__greazy-image">
              <img loading="lazy" src={featuredPhoto.src} alt={featuredPhoto.title} name={featuredPhoto.title}/>
              <img loading="lazy" src={featuredPhoto.src} alt={featuredPhoto.title} name={featuredPhoto.title}/>
              <img loading="lazy" src={featuredPhoto.src} alt={featuredPhoto.title} name={featuredPhoto.title}/>
              <img loading="lazy" src={featuredPhoto.src} alt={featuredPhoto.title} name={featuredPhoto.title}/>
            </div>
            :
            <p>loading...</p>
        }
        <div className="about__greazy-info">
          <h2 className="about__greazy-info__title">ANYTIME IS A GOOD TIME</h2>
          <p className="about__greazy-info__descripton">En Greazy rompemos con todo aquello que nos diga cómo y cuándo vestirnos, buscando expresar frescura y crudeza en nuestros diseños y movimientos, demostrando así que cualquiera puede pertenecer a Greazy Gang.</p>
        </div>
      </section>
      {
        galleryPhotos &&
        <Gallery galleryPhotos={galleryPhotos}/>
      }
    <section className="contact">
      <div className="contact__box">
        <div className="contact__box__redes"><a href="https://www.instagram.com/__greazy__/?hl=es-la" target="_blank" rel="noopener" alt="Enlace a instagram" name="Enlace a instagram"><i className="fab fa-instagram"></i></a><a href="https://www.facebook.com/Greazy-streetwear-101671948261008" target="_blank" rel="noopener" alt="Enlace a facebook" name="Enlace a facebook"><i className="fab fa-facebook-f"></i></a><a href="https://api.whatsapp.com/send?phone=573226330880&amp;text=Hola%20vengo%20de%20la%20p%C3%A1gina%20web%20y%20me%20interesaría%20conocer%20m%C3%A1s%20de%20ustedes" target="_blank" rel="noopener" alt="Enlace a Whatsapp" name="Enlace a Whatsapp"><i className="fab fa-whatsapp"></i></a></div>
      </div>
    </section>
    <footer className="footer"><span className="rights">® 2021 by Greazy</span></footer>
    </div>
  )
}
